# Report Change Log {-}

### fish_passage_skeena_2022_reporting v0.1.1 (20240513) {-}

- Update "Alvin Creek" memo (Tributary to Owen Creek - 197379) to include 2023 sampling attempt and brief detail of Bii Wenii recovery/restoration initiative.  Correct the road km to 29.8. Update fish species list to include all species observed in 2023. Include cost estimate section with estimate of cost updated by hand to align with Marc Dewit's estimate.
- Update Sterrit Creek - 198225 with 2023 site visit information (ie. natural barrier at outlet negating value of replacing the structure)
- Update Dale Creek - 198215 with 2023 electrofishing data
- Update Tributary to Skeena River - 198216 & 198217 -  Sik-E-Dakh (Glen Vowell) with 2023 electrofishing data and cost estimate
from 
- fix interactive map so names of watershed groups show up correctly on hover
- Update cost estimate for unpaved resource roads to 30k/per m to better reflect inflated prices in 2024.
- Correct error in cost estimates that had massive overestimates of gain per dollar.
- Include cost estimate table in Results section.


### fish_passage_skeena_2022_reporting v0.1.0 {-}

- update crossings layer or `bcfishpass` object as per https://github.com/NewGraphEnvironment/fish_passage_skeena_2022_reporting/issues/120
- correct modelling for Sandstone 8430
